import React from 'react'

export default function AnaSayfa() {
  return (
    <div className='hakkimizda'>
        <h1 style={{marginBottom:"3rem"}}>Burası Hakkımızda Sayfası</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique quaerat vel inventore consectetur consequuntur nesciunt odit doloribus asperiores voluptas ducimus! Corrupti porro obcaecati error, velit iusto repudiandae rerum dicta nam placeat quaerat, possimus commodi ab qui iure nostrum vel eum recusandae beatae, at est sunt sapiente minima dolores. Accusamus magni ea delectus hic ratione consectetur, vitae quisquam est nulla qui dolore similique enim ipsa tempora velit neque laborum perspiciatis deserunt nesciunt minus ad! Vero rem, necessitatibus illum quis, omnis repellat earum amet distinctio quidem autem magnam iure nostrum ratione inventore. Distinctio, maiores? Inventore ex animi reprehenderit sed repudiandae vel ab, illum sunt, distinctio fugiat deleniti, mollitia voluptate rerum soluta necessitatibus beatae accusamus asperiores. Suscipit porro illo voluptatibus, repellat, debitis corporis eum distinctio laudantium quos, alias dolorum placeat perferendis sunt officia consequatur nobis. Doloribus optio mollitia consectetur debitis dolor illum tempora at reiciendis quam blanditiis! Perspiciatis aut sunt earum quas fugiat, aliquid commodi a consectetur rerum esse quibusdam sequi dolorum provident natus tempora, soluta iste nam. Dolorum, illo hic voluptas laborum reiciendis laboriosam dignissimos, vero impedit nisi nobis delectus esse minus id dolor? Iste quam in assumenda. Ipsam dolore dicta unde molestiae, corrupti iure earum eius fugiat nostrum repudiandae error, quasi libero, explicabo beatae commodi amet veritatis enim accusantium eaque! Illo accusantium laboriosam unde ipsum aliquid. Obcaecati facere accusamus incidunt, voluptatem cupiditate quia ab error ullam, laudantium veniam cum illum rem reiciendis maiores amet optio delectus! Quasi quo odio nemo quaerat repellendus temporibus nesciunt modi libero at nobis eius quas fuga iure veniam incidunt ipsam quisquam illum atque numquam, animi sit ullam itaque ducimus? Tempore facilis asperiores totam beatae nisi expedita optio nihil tenetur, nemo ut temporibus incidunt repudiandae sequi sit vel cupiditate voluptate, alias numquam ratione quod, reiciendis sapiente cum commodi. Dignissimos incidunt praesentium suscipit impedit necessitatibus eum debitis facilis.</p>
    </div>
  )
}
